### ISSUE TITLE
Reactie op artikel in Accountant.nl d.d. 8-8-2023

### ISSUE THREAD

**Issue by hkinds** [Abmvk/kmc#1]
In AWK zou de code als volgt luiden:

BEGIN	{
	system("cls")
	printf("Leeftijd: ") > "CON"
	getline leeftijd < "CON"
	printf("Naam: ") > "CON"
	getline naam < "CON"
	naam=substr(naam,1,10)
	while(geboortejaar !~ /[1-2][0-9][0-9][0-9]/)	{
		printf("Geboortejaar: ")
		getline geboortejaar < "CON"
	}
	timetab(t,time())
	printf("\n\nNaam: %s\nLeeftijd: %d\nGeboortejaar: %d\n\n", naam, leeftijd, geboortejaar)
	if(t["YEAR"]-leeftijd-geboortejaar>1)
		printf("Klopt je leeftijd wel?\n\n")
	else
		printf("Je leeftijd zou kunnen kloppen\n\n")
}

awk file en gecompileerde exe toegevoegd in zip bestand als bijlage.

Harold Kinds
[kmk1.zip](https://github.com/Abmvk/kmc/files/12328000/kmk1.zip)

**Comment by Abmvk** [comment]
Dank!Met vriendelijke groet,Arnout van KempenOp 12 aug. 2023 om 20:04 heeft hkinds ***@***.***> het volgende geschreven:﻿
In AWK zou de code als volgt luiden:
BEGIN	{
system("cls")
printf("Leeftijd: ") > "CON"
getline leeftijd < "CON"
printf("Naam: ") > "CON"
getline naam < "CON"
naam=substr(naam,1,10)
while(geboortejaar !~ /[1-2][0-9][0-9][0-9]/)	{
printf("Geboortejaar: ")
getline geboortejaar < "CON"
}
timetab(t,time())
printf("\n\nNaam: %s\nLeeftijd: %d\nGeboortejaar: %d\n\n", naam, leeftijd, geboortejaar)
if(t["YEAR"]-leeftijd-geboortejaar>1)
printf("Klopt je leeftijd wel?\n\n")
else
printf("Je leeftijd zou kunnen kloppen\n\n")
}
awk file en gecompileerde exe toegevoegd in zip bestand als bijlage.
Harold Kinds
kmk1.zip
